// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUvgOorMa3HblNi8p5xCDAxwupn2xdX4c',
    appId: '1:98160967216:web:7278bcdf41ff5867a4f7f5',
    messagingSenderId: '98160967216',
    projectId: 'prakflutterfirebase-6a09d',
    authDomain: 'prakflutterfirebase-6a09d.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-6a09d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDgU_K2YHnxOjAhBE2xILzd7QYTXL3tRw',
    appId: '1:98160967216:android:79c906803434e1e0a4f7f5',
    messagingSenderId: '98160967216',
    projectId: 'prakflutterfirebase-6a09d',
    storageBucket: 'prakflutterfirebase-6a09d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8zlapavwJNzgBGATh_g9C3T65rHiZdAY',
    appId: '1:98160967216:ios:92d7f37c78953b6fa4f7f5',
    messagingSenderId: '98160967216',
    projectId: 'prakflutterfirebase-6a09d',
    storageBucket: 'prakflutterfirebase-6a09d.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8zlapavwJNzgBGATh_g9C3T65rHiZdAY',
    appId: '1:98160967216:ios:92d7f37c78953b6fa4f7f5',
    messagingSenderId: '98160967216',
    projectId: 'prakflutterfirebase-6a09d',
    storageBucket: 'prakflutterfirebase-6a09d.appspot.com',
    iosBundleId: 'com.example.praktikum9',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDUvgOorMa3HblNi8p5xCDAxwupn2xdX4c',
    appId: '1:98160967216:web:7eda56b0b1f0221ba4f7f5',
    messagingSenderId: '98160967216',
    projectId: 'prakflutterfirebase-6a09d',
    authDomain: 'prakflutterfirebase-6a09d.firebaseapp.com',
    storageBucket: 'prakflutterfirebase-6a09d.appspot.com',
  );
}
